#!/bin/sh -ex

SRC=/usr/local/src
GAE_JAVA=/var/www/google_appengine

# configure java
JVM=java-6-openjdk
update-java-alternatives -s $JVM || true
echo JAVA_HOME=\"/usr/lib/jvm/${JVM}\" >> /etc/environment

NAME=appengine-java-sdk
unzip $SRC/$NAME-*.zip -d $SRC; rm $SRC/$NAME-*.zip
mv -T $SRC/$NAME-* $GAE_JAVA
chown -R root:root $GAE_JAVA

# unpack google web kit (GWT)
NAME=gwt-*.zip
unzip $SRC/$NAME -d $GAE_JAVA/demos; rm $SRC/$NAME
cd $GAE_JAVA/demos
ln -s gwt-* gwt
cd -

# preconfigure demos build.properties
for d in $(ls $GAE_JAVA/demos); do
cat >$GAE_JAVA/demos/$d/build.properties<<EOF
gwt.sdk=../gwt
appengine.sdk=../..
EOF
done

# tweak tkl-webcp
sed -i "s|width: 520px;|width: 580px;|" /var/www/css/base.css

# clean up
rm -rf $SRC/*

